# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and canary builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denoland/setup-deno

name: Action

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        node: [14.x]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - if: github.event == 'push'
        run: sleep 15

      - if: github.event == 'pull request'
        run: sleep 18

      - name: Get Current Time
        uses: 1466587594/get-current-time@v2.0.0
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+01:00"

      - name: Add PR comment
      - if: github.event == 'pull request'
        env:
          TIME: "${{ steps.current-time.outputs.second }}"
        run: echo "The CI took ${{$TIME}} seconds"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build --if-present
